// ITQuestions100.jsx
export const ITQuestions100 = [
  // --- Programming ---
  {
    id: 1,
    topic: "Programming",
    question: "Which of the following is a valid Java variable name?",
    options: { A: "1variable", B: "variable_1", C: "var-name", D: "void" },
    answer: "B",
  },
  {
    id: 2,
    topic: "Programming",
    question: "What is the output of: console.log(typeof null) in JavaScript?",
    options: { A: "null", B: "object", C: "undefined", D: "number" },
    answer: "B",
  },
  {
    id: 3,
    topic: "Programming",
    question: "Which Python data structure is immutable?",
    options: { A: "List", B: "Dictionary", C: "Tuple", D: "Set" },
    answer: "C",
  },
  {
    id: 4,
    topic: "Programming",
    question: "Which operator is used for comparison in C++?",
    options: { A: "=", B: "==", C: "===", D: "!=" },
    answer: "B",
  },
  {
    id: 5,
    topic: "Programming",
    question: "Which loop is guaranteed to execute at least once?",
    options: { A: "for", B: "while", C: "do-while", D: "foreach" },
    answer: "C",
  },
  {
    id: 6,
    topic: "Programming",
    question: "Which method is used to add an element to the end of a Python list?",
    options: { A: "add()", B: "append()", C: "push()", D: "insert()" },
    answer: "B",
  },
  {
    id: 7,
    topic: "Programming",
    question: "What is the default access modifier in Java if none is specified?",
    options: { A: "private", B: "public", C: "protected", D: "package-private" },
    answer: "D",
  },
  {
    id: 8,
    topic: "Programming",
    question: "Which JavaScript keyword declares a block-scoped variable?",
    options: { A: "var", B: "let", C: "const", D: "both B and C" },
    answer: "D",
  },
  {
    id: 9,
    topic: "Programming",
    question: "What does 'OOP' stand for in programming?",
    options: { A: "Object-Oriented Programming", B: "Open Operations Protocol", C: "Order of Processing", D: "Operational Output Program" },
    answer: "A",
  },
  {
    id: 10,
    topic: "Programming",
    question: "Which of the following is NOT a primitive data type in Java?",
    options: { A: "int", B: "float", C: "String", D: "boolean" },
    answer: "C",
  },
  {
    id: 11,
    topic: "Programming",
    question: "In Python, what does the 'len()' function do?",
    options: { A: "Counts elements in a list", B: "Calculates sum", C: "Converts to integer", D: "Prints the list" },
    answer: "A",
  },
  {
    id: 12,
    topic: "Programming",
    question: "Which C++ feature allows a function to have multiple definitions?",
    options: { A: "Encapsulation", B: "Polymorphism", C: "Function Overloading", D: "Inheritance" },
    answer: "C",
  },
  {
    id: 13,
    topic: "Programming",
    question: "Which Python keyword is used for exception handling?",
    options: { A: "catch", B: "try", C: "except", D: "final" },
    answer: "B",
  },
  {
    id: 14,
    topic: "Programming",
    question: "Which of these is a frontend JavaScript framework?",
    options: { A: "Django", B: "React", C: "Flask", D: "Spring" },
    answer: "B",
  },
  {
    id: 15,
    topic: "Programming",
    question: "Which is used to create an infinite loop in C?",
    options: { A: "for(;;)", B: "while(1)", C: "both A and B", D: "None" },
    answer: "C",
  },

  // --- Databases ---
  {
    id: 16,
    topic: "Databases",
    question: "Which SQL command is used to remove a table?",
    options: { A: "DELETE TABLE", B: "DROP TABLE", C: "REMOVE TABLE", D: "TRUNCATE TABLE" },
    answer: "B",
  },
  {
    id: 17,
    topic: "Databases",
    question: "What is a primary key in a database?",
    options: { A: "A column that allows duplicate values", B: "A unique identifier for table rows", C: "A type of index", D: "A database user" },
    answer: "B",
  },
  {
    id: 18,
    topic: "Databases",
    question: "Which is a NoSQL database?",
    options: { A: "MySQL", B: "MongoDB", C: "PostgreSQL", D: "SQLite" },
    answer: "B",
  },
  {
    id: 19,
    topic: "Databases",
    question: "Which SQL keyword is used to sort the results?",
    options: { A: "SORT BY", B: "ORDER BY", C: "GROUP BY", D: "ARRANGE BY" },
    answer: "B",
  },
  {
    id: 20,
    topic: "Databases",
    question: "Which command is used to add a new row in SQL?",
    options: { A: "INSERT INTO", B: "ADD ROW", C: "UPDATE", D: "CREATE ROW" },
    answer: "A",
  },
  {
    id: 21,
    topic: "Databases",
    question: "What does ACID stand for in databases?",
    options: { A: "Atomicity, Consistency, Isolation, Durability", B: "Access, Control, Integrity, Data", C: "Atomicity, Control, Isolation, Data", D: "Availability, Consistency, Integrity, Durability" },
    answer: "A",
  },
  {
    id: 22,
    topic: "Databases",
    question: "Which SQL statement is used to modify existing data?",
    options: { A: "UPDATE", B: "MODIFY", C: "CHANGE", D: "ALTER" },
    answer: "A",
  },
  {
    id: 23,
    topic: "Databases",
    question: "Which clause is used to filter results in SQL?",
    options: { A: "WHERE", B: "HAVING", C: "FILTER", D: "SELECT" },
    answer: "A",
  },
  {
    id: 24,
    topic: "Databases",
    question: "Which key uniquely identifies each record in a table?",
    options: { A: "Foreign Key", B: "Primary Key", C: "Candidate Key", D: "Composite Key" },
    answer: "B",
  },
  {
    id: 25,
    topic: "Databases",
    question: "Which SQL function calculates the total sum of a column?",
    options: { A: "SUM()", B: "TOTAL()", C: "COUNT()", D: "ADD()" },
    answer: "A",
  },

  // --- Networking ---
  {
    id: 26,
    topic: "Networking",
    question: "What is the default port for HTTP?",
    options: { A: "80", B: "443", C: "21", D: "25" },
    answer: "A",
  },
  {
    id: 27,
    topic: "Networking",
    question: "Which protocol is used to send emails?",
    options: { A: "SMTP", B: "FTP", C: "HTTP", D: "DNS" },
    answer: "A",
  },
  {
    id: 28,
    topic: "Networking",
    question: "What does DNS stand for?",
    options: { A: "Dynamic Name System", B: "Domain Name System", C: "Data Network Service", D: "Direct Network Service" },
    answer: "B",
  },
  {
    id: 29,
    topic: "Networking",
    question: "Which layer of the OSI model handles routing?",
    options: { A: "Transport", B: "Network", C: "Application", D: "Data Link" },
    answer: "B",
  },
  {
    id: 30,
    topic: "Networking",
    question: "Which device is used to connect multiple networks?",
    options: { A: "Switch", B: "Router", C: "Hub", D: "Access Point" },
    answer: "B",
  },

  // --- Cybersecurity ---
  {
    id: 31,
    topic: "Cybersecurity",
    question: "What is phishing?",
    options: { A: "A network protocol", B: "A type of cyber attack", C: "A firewall type", D: "A malware program" },
    answer: "B",
  },
  {
    id: 32,
    topic: "Cybersecurity",
    question: "Which algorithm is used in AES encryption?",
    options: { A: "RSA", B: "DES", C: "Advanced Encryption Standard", D: "SHA-256" },
    answer: "C",
  },
  {
    id: 33,
    topic: "Cybersecurity",
    question: "What does VPN stand for?",
    options: { A: "Virtual Private Network", B: "Verified Private Node", C: "Virtual Protected Network", D: "Virtual Personal Node" },
    answer: "A",
  },
  {
    id: 34,
    topic: "Cybersecurity",
    question: "Which malware restricts access to files until a ransom is paid?",
    options: { A: "Virus", B: "Trojan", C: "Ransomware", D: "Spyware" },
    answer: "C",
  },
  {
    id: 35,
    topic: "Cybersecurity",
    question: "Which protocol is commonly used for secure web browsing?",
    options: { A: "HTTP", B: "HTTPS", C: "FTP", D: "SMTP" },
    answer: "B",
  },

  // --- Cloud & DevOps ---
  {
    id: 36,
    topic: "Cloud",
    question: "What is Docker used for?",
    options: { A: "Virtual Machines", B: "Containerization", C: "Database Management", D: "Version Control" },
    answer: "B",
  },
  {
    id: 37,
    topic: "Cloud",
    question: "What does CI/CD stand for?",
    options: { A: "Continuous Integration / Continuous Deployment", B: "Cloud Infrastructure / Cloud Development", C: "Compute Instance / Container Deployment", D: "Code Inspection / Code Distribution" },
    answer: "A",
  },
  {
    id: 38,
    topic: "Cloud",
    question: "Which AWS service is used for object storage?",
    options: { A: "EC2", B: "S3", C: "RDS", D: "Lambda" },
    answer: "B",
  },
  {
    id: 39,
    topic: "Cloud",
    question: "Which tool is used for infrastructure as code?",
    options: { A: "Terraform", B: "Docker", C: "Kubernetes", D: "Jenkins" },
    answer: "A",
  },
  {
    id: 40,
    topic: "Cloud",
    question: "Which Kubernetes object defines a set of pods?",
    options: { A: "Deployment", B: "Service", C: "Ingress", D: "ConfigMap" },
    answer: "A",
  },

  // --- Web Development ---
  {
    id: 41,
    topic: "Web Development",
    question: "Which React hook is used for state management?",
    options: { A: "useEffect", B: "useState", C: "useReducer", D: "useContext" },
    answer: "B",
  },
  {
    id: 42,
    topic: "Web Development",
    question: "Which tag is used to create a hyperlink in HTML?",
    options: { A: "<link>", B: "<a>", C: "<href>", D: "<url>" },
    answer: "B",
  },
  {
    id: 43,
    topic: "Web Development",
    question: "Which CSS property is used to change text color?",
    options: { A: "color", B: "font-color", C: "text-color", D: "background-color" },
    answer: "A",
  },
  {
    id: 44,
    topic: "Web Development",
    question: "Which HTTP method is used to retrieve data from a server?",
    options: { A: "POST", B: "GET", C: "PUT", D: "DELETE" },
    answer: "B",
  },
  {
    id: 45,
    topic: "Web Development",
    question: "Which HTML tag is used to display a table row?",
    options: { A: "<td>", B: "<tr>", C: "<table>", D: "<th>" },
    answer: "B",
  },
  // --- Continue adding questions up to 100 ---
];
